# Generated by Django 4.1.3 on 2022-11-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_status',
            new_name='status',
        ),
    ]
